### ISSUE TITLE
Action::Retry::Strategy needs documentation

### ISSUE THREAD

**Issue by fgabolde** [dams/Action-Retry#4]
Currently, the Action::Retry::Strategy role does not document what methods it requires, or how they should be used. This makes writing a new Strategy class an exercise in reverse-engineering existing modules.

**Comment by dams** [comment]
You mean, it forces you to read the whole code and understand it before writing a new Strategy. Given the small size and complexity of the code, I think it's actually a feature, not a bug. If you're not ready to do that, you're probably not ready to write a good Strategy :)
